name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ClassicThesis.tex
          continue_on_error: true
          args: -pdf -file-line-error -interaction=nonstopmode
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: thesis.pdf